name: hackernews_api
description: A Flutter package of Hacker News API for accessing top and new stories.
version: 0.0.6
homepage: https://github.com/MarsadMaqsood/hackernews_api

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
